@startuml Gestion Club Sportif

left to right direction
skinparam packageStyle rectangle

actor "Administrateur" as admin
actor "Adhérent" as adherent
actor "Entraîneur" as coach

rectangle "Système de Gestion de Club Sportif" {
  usecase "Gérer les adhérents" as UC1
  usecase "Gérer les activités" as UC2
  usecase "Gérer les paiements" as UC3
  usecase "Générer des rapports" as UC4
  usecase "S'inscrire" as UC5
  usecase "Consulter le planning" as UC6
  usecase "S'inscrire aux activités" as UC7
  usecase "Gérer les équipements" as UC8
  usecase "Gérer les présences" as UC9
}

admin --> UC1
admin --> UC2
admin --> UC3
admin --> UC4
admin --> UC8

adherent --> UC5
adherent --> UC6
adherent --> UC7

coach --> UC9
coach --> UC2

UC1 ..> UC5 : <<include>>
UC2 ..> UC8 : <<include>>
UC2 ..> UC9 : <<include>>

@enduml 